-- ============================================
-- Insert Portfolio Companies Data
-- ============================================
-- This migration inserts the complete portfolio companies data
-- from radical_portfolio_companies.json
--
-- Note: This uses INSERT with ON CONFLICT to make it idempotent
-- You can run this migration multiple times safely
--
-- Optimized for AI/ML use cases:
-- - Rich text descriptions for vector embeddings
-- - Comprehensive categorization for filtering
-- - Founder information for relationship mapping
-- - Timestamps for temporal analysis

-- Insert companies
INSERT INTO companies (
  name,
  slug,
  radical_portfolio_url,
  radical_investment_year,
  radical_all_categories,
  radical_primary_category,
  tagline,
  all_sectors,
  primary_sector,
  description,
  founder_names,
  company_website_url,
  last_scraped_at
) VALUES
  ('Artificial Agency', 'artificial-agency', 'https://radical.vc/portfolio/artificial-agency/', 2023, ARRAY['Software'], 'Software', NULL, ARRAY['Software'], 'Software', 'Artificial Agency is an AI-native video advertising studio that uses AI agent employees to create large volumes of high-quality personalized videos in the places and formats these videos perform best. Their agent employees operate within the studio''s AI company operating system, continuously learning and improving with every project.', ARRAY[]::text[], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Aspect Biosystems', 'aspect-biosystems', 'https://radical.vc/portfolio/aspect-biosystems/', 2020, ARRAY['Biotechnology', 'Healthcare'], 'Biotechnology', 'A platform that prints human tissue to help heal injury and disease', ARRAY['Biotechnology', 'Healthcare'], 'Biotechnology', 'Aspect Biosystems is a private biotechnology company developing bioprinted tissue therapeutics to transform how we treat some of the most challenging diseases and injuries. Aspect has built a proprietary new class of 3D bioprinting technology that enables the creation of 3D tissues. Current tissues are being engineered for applications in metabolic and endocrine disease, neurological disease, and arthritis. In July 2025, Aspect announced a $115 million USD Series B financing in partnership with Novo Nordisk – this was the largest deal in bioprinting history.', ARRAY['Tamer Mohammed', 'Sam Wadsworth', 'Simon Beyer'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Attuned Intelligence', 'attuned-intelligence', 'https://radical.vc/portfolio/attuned-intelligence/', 2025, ARRAY['Healthcare'], 'Healthcare', 'Transforming hospital access with supervised AI voice agents', ARRAY['Healthcare'], 'Healthcare', 'Attuned Intelligence is transforming healthcare access with supervised AI voice agents that reduce wait times and increase patient satisfaction. The company''s platform helps hospitals manage high volumes of patient calls while maintaining service quality and staff wellbeing. By combining advanced voice AI with human supervision, Attuned ensures accuracy and empathy in patient interactions.', ARRAY['Domenic Donato', 'Matt Willis'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('CentML', 'centml', 'https://radical.vc/portfolio/centml/', 2022, ARRAY['Semiconductors', 'Software'], 'Semiconductors', 'Better Performance. Less Compute.', ARRAY['Semiconductors', 'Software'], 'Semiconductors', 'Access to compute represents one of the greatest and most persistent bottlenecks for AI. The demands of training state-of-the-art machine learning models are growing exponentially, but the compute required to support this training is not. CentML provides tools that improve ML performance and lower costs by leveraging deep expertise in ML systems software, compilers, and kernel development. By enabling faster training and more efficient inference, CentML is helping build a more scalable AI infrastructure stack.', ARRAY['Gennady Pekhimenko', 'Shang (Sam) Wang', 'Anand Jayarajan', 'Akbar Nurlybaev'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Chemix', 'chemix', 'https://radical.vc/portfolio/chemix/', 2021, ARRAY['Climate', 'Energy', 'Materials'], 'Climate', 'Powering the future with more efficient and sustainable batteries', ARRAY['Climate', 'Energy', 'Materials'], 'Climate', 'Chemix''s mission is to accelerate the development of sustainable battery chemistry. By using AI to develop breakthrough EV battery technologies, Chemix aims to eliminate the reliance on rare earth minerals without compromising vehicle performance.', ARRAY['Kaixiang Lin', 'Jason Koeller'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('ClimateAi', 'climateai', 'https://radical.vc/portfolio/climateai/', 2021, ARRAY['Climate', 'Supply Chain'], 'Climate', 'ClimateAi is building the industry''s first enterprise climate planning platform', ARRAY['Climate', 'Supply Chain'], 'Climate', 'ClimateAi is a pioneer in applying artificial intelligence to climate risk modelling, offering best-in-class extreme weather and climate prediction combined with industry specific operational insights. ClimateAi is a game changer for companies looking to better predict production, supply and demand challenges. With its AI-based solutions, businesses can make operational decisions that adapt to near-term weather changes and long-term climate shifts.', ARRAY['Himanshu Gupta'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Cohere', 'cohere', 'https://radical.vc/portfolio/cohere/', 2020, ARRAY['LLMs', 'Software'], 'LLMs', 'Unlocking Natural Language Processing', ARRAY['LLMs', 'Software'], 'LLMs', 'Cohere was founded to make it possible for machines to understand and use human language. Our interactions with software and machines are growing exponentially – from our personal devices, to businesses, to the manufacturing and transportation systems that surround us. Yet these interactions remain mostly based on rigid user interfaces like buttons and menus, rather than on the shared language humans use to communicate. Large Language Models (LLMs) represent a fundamental breakthrough. Because they are trained on text and can predict which words should come next, LLMs make it possible for machines to ''understand'' the meaning of language and generate text. This means that any piece of technology can suddenly become more conversational, and can become empowered with knowledge it previously didn''t have. Co-founded by AI researcher Dr. Aidan Gomez along with Nick Frosst and Ivan Zhang, Cohere is applying LLMs to accelerate and empower many different kinds of work. It is building on Aidan''s experience as a co-author of the ''Attention is All You Need'' paper, which has become a field-defining publication and foundational technique in NLP. Cohere is creating LLM-based products that accelerate productivity, and make it possible for us to interact with technology as we do with other humans.', ARRAY['Aidan Gomez', 'Nick Frosst', 'Ivan Zhang'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Covariant', 'covariant', 'https://radical.vc/portfolio/covariant/', 2020, ARRAY['Robotics', 'Supply Chain'], 'Robotics', 'Universal AI platform for robotics', ARRAY['Robotics', 'Supply Chain'], 'Robotics', 'From food distribution to healthcare to e-commerce, the global supply chain is facing unprecedented pressure to deliver orders quickly, reliably and efficiently, while keeping workers safe. Automation is the key to meeting those challenges. While repetitive and predictable tasks like the movement of goods have successfully been automated, complex and unpredictable tasks that require hands, such as picking, placing and unloading, have not. Traditional automation can''t handle the constant change and infinite variability of these tasks. Automating them requires advanced AI that can understand, learn and adapt. Founded in 2017, Covariant is building the Covariant Brain, universal AI that enables robots to see, reason and act autonomously in the real world. Covariant robots learn general abilities such as robust 3D perception, physical affordances of objects, few-shot learning and real-time motion planning which gives them the intelligence to learn how to manipulate new objects they''ve never seen before in environments where they''ve never operated. With a world leading team of AI researchers and robotocists, Covariant has built a universal artificial intelligence platform that will reshape the future of robotics. We expect Covariant to create a global standard for the deployment and adoption of robotics across many facets of the economy.', ARRAY['Pieter Abbeel', 'Peter Chen', 'Rocky Duan', 'Tianhao Zhang'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Crusoe', 'crusoe', 'https://radical.vc/portfolio/crusoe/', 2025, ARRAY['Infrastructure'], 'Infrastructure', 'Building AI Factories', ARRAY['Infrastructure'], 'Infrastructure', 'Crusoe Energy is a leading developer of AI-optimized data center infrastructure, building the physical foundation that powers today''s AI revolution. The company specializes in constructing large-scale, purpose-built data centers designed specifically for AI workloads. Crusoe''s competitive advantage lies in its unparalleled access to energy resources, deep vertical integration, and supply chain expertise, enabling the company to build gigawatt-scale AI data centers faster and at larger scales than competitors. The company has partnered with several of the world''s largest technology companies, including OpenAI, for whom Crusoe is developing the massive "Stargate" data center in Abilene, Texas. In addition to its data center development business, Crusoe operates a rapidly growing cloud computing platform, providing comprehensive cloud services to many of the world''s leading AI companies. Co-founded by Chase Lochmiller and Cully Cavness, Crusoe stands at the center of the largest capital investment in human history.', ARRAY['Chase Lochmiller', 'Cully Cavness'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('DatologyAI', 'datologyai', 'https://radical.vc/portfolio/datologyai/', 2023, ARRAY['Data'], 'Data', 'Better data, better models, better business.', ARRAY['Data'], 'Data', 'AI models are a reflection of the data on which they are trained – models are what they eat. The specifics of the data on which a model is trained generally has a far greater impact on that model''s performance than the specifics of the model''s architecture. Training models on the right data can drive dramatic improvements in model performance and – just as importantly – in model efficiency. Data curation for self-supervised learning remains a challenging, cutting-edge research problem, one that only the world''s top AI research labs are able to do effectively. Until now. DatologyAI was founded to democratize this critical part of the AI infrastructure stack, making model training more accessible to all through better data.', ARRAY['Ari Morcos', 'Matthew Leavitt', 'Bogdan Gaza'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Delphina', 'delphina', 'https://radical.vc/portfolio/delphina/', 2023, ARRAY['Data', 'Software'], 'Data', 'Power Tools for Data Science', ARRAY['Data', 'Software'], 'Data', 'Much of what knowledge workers do every day, across industries and across functions, is routine, predictable and formulaic. One of the clearest commercial opportunities for large language models (LLMs) is to streamline and automate broad swaths of white-collar work. Similar to software engineering, "traditional" machine learning and data science represent complex but learnable activities that today''s language models are well-suited to tackle. Backed by a proven team of data scientists and engineers, Delphina is a copilot for data science that speeds predictive AI model building and deployment. By democratizing the ability to do sophisticated data science, Delphina will drive immense productivity gains and value creation for any organization, large or small, that deals in data – which, in 2023, means pretty much every organization on earth.', ARRAY['Jeremy Hermann', 'Duncan Gilchrist'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Emerald AI', 'emerald-ai', 'https://radical.vc/portfolio/emerald-ai/', 2024, ARRAY['Software'], 'Software', 'Transforming energy-intensive data centers into AI-powered grid allies', ARRAY['Software'], 'Software', 'Emerald AI is revolutionizing data center operations with AI-powered software that transforms energy-intensive facilities from inflexible grid liabilities into responsive energy assets. Their platform enables data centers to reduce power consumption by 25% or more during peak demand periods while maintaining AI compute performance, unlocking new capacity on existing grid infrastructure. Founded by world-leading energy expert and CEO Varun Sivaram, a Rhodes Scholar and physicist with senior experience across Fortune 500 renewables, government policy, and academia, Emerald AI emerged from Radical Ventures with $24.5M in funding led by top-tier investors including Nvidia, Google Chief Scientist Jeff Dean, and former Secretary of State John Kerry.', ARRAY['Dr. Varun Sivaram'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Firsthand', 'firsthand', 'https://radical.vc/portfolio/firsthand/', 2023, ARRAY['Software'], 'Software', 'The AI platform that gives publishers and brands full control over their data and content', ARRAY['Software'], 'Software', 'Firsthand allows publishers to create and distribute their own AI agents and chatbots directly with consumers everywhere online. Content creators can protect, control, and deploy their data across these 1:1 personalized conversations powered anywhere a consumer is seeking information. At the core of Firsthand is Lakebed, the company''s AI rights and data management platform. With Lakebed, publishers and brands can protect their knowledge assets and retain complete control over where, when, and by whom their content is surfaced through AI.', ARRAY['Jonathan Heller', 'Michael Rubenstein', 'Wei Wei'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Genesis Therapeutics', 'genesis-therapeutics', 'https://radical.vc/portfolio/genesis-therapeutics/', 2020, ARRAY['Biotechnology', 'Healthcare', 'Materials'], 'Biotechnology', 'Unifying AI and Biotech', ARRAY['Biotechnology', 'Healthcare', 'Materials'], 'Biotechnology', 'Genesis Therapeutics pairs proven drug developers with the industry''s most advanced small molecule discovery platform. A world class team of drug developers, AI researchers and software engineers, Genesis Therapeutics is using AI to create transformative therapies for patients.', ARRAY['Evan Feinberg', 'Ben Sklaroff'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Hebbia', 'hebbia', 'https://radical.vc/portfolio/hebbia/', 2022, ARRAY['Financial Services', 'LLMs', 'Search', 'Software'], 'Financial Services', 'Reinventing search by unlocking the vast opportunity of understanding unstructured data', ARRAY['Financial Services', 'LLMs', 'Search', 'Software'], 'Financial Services', 'Hebbia''s AI platform is capable of reading and comprehending the untouched universe of unstructured, private data. Its ''neural search'' enables a user to ask questions using natural language, with Hebbia searching all available data to provide answers immediately and accurately. Hebbia outperforms the current state of the art in machine learning information retrieval by an average of 57%. Hebbia''s software can index any document type — scanned PDFs, spreadsheets, transcripts — transforming into an expert search engine for almost any form of language-based data. From broad market research to targeted information extraction, Hebbia automates diligence workflows, acting as an AI Analyst and instantly surfacing deal points even humans miss.', ARRAY['George Sivulka'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Intrepid Labs', 'intrepid-labs', 'https://radical.vc/portfolio/intrepid-labs/', 2023, ARRAY['Healthcare'], 'Healthcare', 'Fast-tracking drug development for better patient outcomes', ARRAY['Healthcare'], 'Healthcare', 'Intrepid Labs is revolutionizing drug formulation through its AI-driven robotic platform that accelerates pharmaceutical development from months to days. The University of Toronto spinout combined machine learning and robotics to develop Valiant, its modular AI-driven robotic laboratory that autonomously selects, prepares, and analyzes drug formulations. Unlike traditional trial-and-error approaches, Intrepid''s platform screens vast formulation possibilities simultaneously, enabling the intentional design of delivery format, dosing frequency, and patient experience from day one.', ARRAY['Prof. Christine Allen', 'Dr. Pauric Bannigan', 'Dr. Riley Hickman'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Latent Labs', 'latent-labs', 'https://radical.vc/portfolio/latent-labs/', 2024, ARRAY['Biotechnology', 'Software'], 'Biotechnology', 'Frontier models for all molecules of life', ARRAY['Biotechnology', 'Software'], 'Biotechnology', 'Latent Labs is pioneering the next frontier of computational biology, building AI foundation models to make biology programmable through de novo protein design. The company''s generative AI platform enables the creation of entirely new proteins from scratch, moving beyond the limitations of naturally occurring proteins to design therapeutic molecules with precisely tailored properties and functions. Founded by Simon Kohl, a key architect of DeepMind''s Nobel Prize-winning AlphaFold2 system, alongside an all-star team of AI researchers and computational biologists from DeepMind, Google, Microsoft, and leading academic institutions, Latent Labs is realizing the vision of purely computational drug discovery where therapeutic candidates can be generated at the push of a button.', ARRAY['Simon Kohl'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Muon Space', 'muon-space', 'https://radical.vc/portfolio/muon-space/', 2022, ARRAY['Software', 'Space'], 'Software', 'Unlocking satellite-based climate intelligence for every business', ARRAY['Software', 'Space'], 'Software', 'The only way organizations can make meaningful decisions around how to respond to climate change and monitor the efficacy of those decisions is to have access to timely, high quality data. For almost every business, gaining access to new, sophisticated data from space remains incredibly difficult. Embarking on missions to collect data from space requires deep satellite and remote sensing expertise to design, build, launch and operate. Turning those new data sets into useful insights requires yet more expertise. Through its turnkey Scientific Earth Observation services, Muon is helping organizations that do not have space competency develop and utilize space-based observations.', ARRAY[]::text[], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Nabla Bio', 'nabla-bio', 'https://radical.vc/portfolio/nabla-bio/', 2023, ARRAY['Biotechnology', 'Materials'], 'Biotechnology', 'Expanding the universe of druggable targets with AI-powered protein design', ARRAY['Biotechnology', 'Materials'], 'Biotechnology', 'Founded by pioneers of protein language modeling, Nabla develops generative models, multiplexed screens, and protein characterization technologies and applies them to design antibodies against the most challenging disease targets, from GPCRs to ion channels.', ARRAY['Surge Biswas', 'Frances Anastassacos'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('OffDeal', 'offdeal', 'https://radical.vc/portfolio/offdeal/', 2024, ARRAY['Financial Services', 'Software'], 'Financial Services', 'AI-Powered Investment Banking Platform for SMB Acquisitions', ARRAY['Financial Services', 'Software'], 'Financial Services', 'OffDeal is an AI-powered investment banking platform dedicated to transforming the SMB M&A process. OffDeal''s proprietary data architecture uses state-of-the-art AI to solve a critical challenge facing the SMB investment banking sector: connecting interested sellers with motivated buyers at scale. By creating a more efficient M&A experience, OffDeal is bringing investment banking into the AI age.', ARRAY['Ori Eldarov', 'Alston Lin'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Orbital Materials', 'orbital-materials', 'https://radical.vc/portfolio/orbital-materials/', 2023, ARRAY['Climate', 'Materials'], 'Climate', 'Advanced materials, made with AI', ARRAY['Climate', 'Materials'], 'Climate', 'Traditional methods of discovering new materials have long relied on time-consuming trial and error processes in the lab, often resulting in years of experimentation before success is achieved. Orbital Materials is revolutionizing this approach by leveraging the power of generative AI to accelerate the material discovery process. At the heart of Orbital Materials'' pioneering approach lies "LINUS", an AI foundation model tailored for materials science. LINUS serves as the backbone of the company''s research laboratory in New Jersey, where it drives the development of a robust pipeline of materials and chemical technologies crucial for facilitating the energy transition. By harnessing LINUS, the company captures the complexity of materials science, facilitating rapid advancements akin to the transformative impact that DeepMind''s AlphaFold has had on protein research.', ARRAY[]::text[], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('P-1 AI', 'p-1-ai-2', 'https://radical.vc/portfolio/p-1-ai-2/', 2025, ARRAY['Software'], 'Software', 'P-1 AI is building engineering AGI for the physical world', ARRAY['Software'], 'Software', 'P-1 AI is building engineering AGI for the physical world through Archie, an AI agent that automates cognitive tasks human engineers perform when designing complex physical systems. The company''s breakthrough approach combines multi-physics reasoning, spatial intelligence, and synthetic training datasets to create AI capable of engineering-level design work. At the core of P-1 AI''s innovation is solving the training data scarcity problem in physical product domains. The company generates large, physics-based synthetic datasets that enable Archie to learn underlying physics and perform quantitative spatial reasoning tasks that mirror human engineering workflows — from distilling design requirements to developing product concepts and performing design trades. Rather than replacing existing engineering tools, P-1 AI focuses on cognitive automation, giving teams an AI teammate that handles repetitive tasks while learning from real-world feedback. The platform will initially deploy in data center cooling systems before expanding to industrial systems, automotive, aerospace, and defence applications.', ARRAY['Paul Eremenko'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Periodic Labs', 'periodic-labs', 'https://radical.vc/portfolio/periodic-labs/', 2025, ARRAY['Software'], 'Software', 'Automating scientific discovery', ARRAY['Software'], 'Software', 'Periodic Labs is building scientific superintelligence to accelerate discovery in the physical sciences. The company''s platform combines frontier AI models, physics-based simulations, and autonomous robotic laboratories to create a closed-loop system where AI scientists can generate hypotheses, design experiments, and learn from outcomes. Founded by Liam Fedus, who co-created ChatGPT at OpenAI, and Dogus Cubuk, who led materials AI at Google DeepMind, Periodic Labs'' mission is to build the technology infrastructure for scientific discovery driven by AI.', ARRAY['Liam Fedus', 'Dogus Cubuk'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Pixxel', 'pixxel', 'https://radical.vc/portfolio/pixxel/', 2022, ARRAY['Climate', 'Software', 'Space'], 'Climate', 'Seeing the Unseen', ARRAY['Climate', 'Software', 'Space'], 'Climate', 'Pixxel is on a mission to build a health monitor for the planet. Pixxel''s hyperspectral imaging platform is capable of diagnosing climate impacts at global scale, providing granular insights to any business that benefits from understanding how the earth is changing. By leveraging their proprietary sensor design, Pixxel is pushing the state of the art on imagery resolution. These images feed powerful, AI-powered predictive models that will be relevant to many industries. Pixxel''s platform unlocks a range of novel environment and sustainability use cases, offering advanced tools for agriculture, oil and gas, mining, and environmental agencies to analyze geospatial composites of the earth''s surface in real-time through a simple API.', ARRAY['Awais Ahmed', 'Kshitij Khandelwel'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Pocket Health', 'pocket-health', 'https://radical.vc/portfolio/pocket-health/', 2020, ARRAY['Healthcare'], 'Healthcare', 'Patient-centered diagnostic image sharing platform', ARRAY['Healthcare'], 'Healthcare', 'Traditional image management systems leave patients on the outside looking in while their doctors and hospitals share data between themselves. This too often fails patients at times when they are most in need. PocketHealth gives patients ownership of their imaging data and equips their hospitals with an industry-leading image management solution. The PocketHealth team is removing hard costs and friction for hospitals and health care providers while fundamentally empowering patients with a simple-to-use platform to participate in their care. Beyond streamlining the medical imaging industry, PocketHealth is showing itself to be a trusted steward of patient health data. Its focus on patient-centered care, privacy and security is a blueprint for the future of the electronic medical records industry.', ARRAY['Rishi Nayyar', 'Harsh Nayyar'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Prepared', 'prepared', 'https://radical.vc/portfolio/prepared/', 2025, ARRAY['Software'], 'Software', 'Accelerating emergency response with assistive AI', ARRAY['Software'], 'Software', 'Prepared has built an AI-powered platform that transforms how 911 centers handle critical calls. The company''s comprehensive solution provides real-time transcription, instant translation across any language, intelligent dispatch assistance, automated non-emergency triage, and quality assurance analytics. Prepared''s platform enables callers to send photos and video footage directly to 911 centers, giving first responders critical visual context before they arrive on scene. The system''s AI-powered translation capabilities reduce emergency response times from 15+ minutes to just minutes by eliminating wait times for interpreters. Advanced AI summarization ensures no critical details are missed during high-stress situations, while improving employee retention in an industry plagued by high turnover and burnout. Currently deployed across more than 1,000 emergency call centers in the United States, including major cities like Las Vegas, Nashville, and Baltimore, Prepared is building toward a vision of near-fully autonomous emergency response systems. The platform leverages AI to handle routine tasks and eliminate friction, allowing human responders to focus on the judgment, instinct, and compassion that define life-saving emergency work.', ARRAY['Michael Chime', 'Neal Soni', 'Dylan Gleicher'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Promise Robotics', 'promise-robotics', 'https://radical.vc/portfolio/promise-robotics/', 2020, ARRAY['Construction', 'Robotics', 'Supply Chain'], 'Construction', 'A fully integrated production platform for the digital manufacturing and assembly of buildings', ARRAY['Construction', 'Robotics', 'Supply Chain'], 'Construction', 'Promise Robotics is transforming how buildings get made, with the aim of creating a more sustainable and affordable built environment. Promise Robotics brings together artificial intelligence, advanced manufacturing, and construction under one roof to create a platform for digital manufacturing. By helping builders, real estate developers, and other industry professionals leverage the efficiencies of industrialized automation, Promise Robotics aims to usher in a new era of sustainable construction.', ARRAY['Ramtin Attar', 'Reza Nasseri'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Reka', 'reka', 'https://radical.vc/portfolio/reka/', 2023, ARRAY['LLMs', 'Software'], 'LLMs', 'An AI research and product company that develops models to benefit humanity, organizations, and enterprises', ARRAY['LLMs', 'Software'], 'LLMs', 'Reka develops generative multimodal models and self-improving agents. Delivering tailored models that reside within the enterprise, Reka offers a novel approach to solving the biggest challenges for deploying generative models (cost, data privacy, energy consumption, etc). Reka''s self-improving multimodal models also power Yasa — an enterprise-grade multimodal assistant. Designed with privacy, security, and efficiency in mind, Yasa is trained to read text, images, videos, and tabular data. It can be used to generate ideas for creative tasks, get answers to basic questions, or derive insights from internal data.', ARRAY[]::text[], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Ribbon', 'ribbon', 'https://radical.vc/portfolio/ribbon/', 2025, ARRAY['Software'], 'Software', 'An AI-powered hiring platform', ARRAY['Software'], 'Software', 'Ribbon is an AI-powered hiring platform designed to fix the broken hiring process. The company uses AI to streamline recruitment while keeping it fair, efficient, and human-centred. At the core of Ribbon''s technology are two key innovations: AI-powered intelligent Interviews that conduct natural, adaptive conversations with candidates in real-time and Smart Hiring Analytics that provide instant feedback and data-driven insights to hiring teams. The platform allows candidates to complete interviews anytime, eliminating scheduling delays and improving accessibility for working parents and students.', ARRAY['Arsham Ghahramani', 'Dave Vu'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('RoadBotics', 'roadbotics', 'https://radical.vc/portfolio/roadbotics/', 2019, ARRAY['Infrastructure'], 'Infrastructure', 'Smart diagnostics for infrastructure', ARRAY['Infrastructure'], 'Infrastructure', 'Assessing roads has been done the same way for thousands of years, with people riding around and subjectively determining what to fix and when. Billions of dollars in road maintenance costs are spent every year relying on an antiquated system – an enormous financial cost mostly borne by governments and taxpayers. RoadBotics'' computer vision platform enables a smartphone, placed on a vehicle dashboard, to collect images of road surfaces, predict road damage and to prioritize repairs in a colour-coded map. RoadBotics is already delivering efficiencies to city managers and road owners, offering comprehensive infrastructure assessments at scale. Additionally, RoadBotics provides communities a mechanism to visualize, plan and communicate priorities to their constituents, bringing an unprecedented level of transparency to key infrastructure decisions. RoadBotics is a perfect example of Artificial Intelligence fixing an enormous global problem. It reduces costs and improves lives.', ARRAY['Benjamin Schmidt'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Signal 1', 'signal-1', 'https://radical.vc/portfolio/signal-1/', 2022, ARRAY['Healthcare'], 'Healthcare', 'Transforming hospitals with AI', ARRAY['Healthcare'], 'Healthcare', 'Hospitals today face unprecedented challenges, from surgical backlogs to staffing shortages. Signal 1''s AI platform integrates AI-driven insights directly into existing workflows, delivering improved patient outcomes, enhanced hospital efficiency and reduced stress for front-line workers.', ARRAY['Tomi Poutanen', 'Dr. Muhammad Mamdani', 'Mara Lederman'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Slingshot AI', 'slingshot-ai', 'https://radical.vc/portfolio/slingshot-ai/', 2025, ARRAY['Healthcare'], 'Healthcare', 'Mental health research lab building a foundation model for psychology', ARRAY['Healthcare'], 'Healthcare', 'Slingshot AI is revolutionizing mental health care through Ash, an app powered by the first AI foundation model purpose-built specifically for therapy. Unlike general-purpose language models adapted for therapeutic use, Slingshot has developed a specialized AI system trained from the ground up on the expertise of mental health practitioners. At the core of Slingshot''s innovation is its comprehensive approach to therapeutic AI, combining the largest dataset of behavioral health data ever collected with advanced reinforcement learning techniques. The system learns from every conversation, creating feedback loops that continuously improve therapeutic outcomes based on what actually helps users achieve long-term behavioral changes.', ARRAY['Neil Parikh', 'Daniel Reid Cahn'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Spara', 'spara', 'https://radical.vc/portfolio/spara/', 2024, ARRAY['Software'], 'Software', 'AI-powered inbound conversion platform for enterprise', ARRAY['Software'], 'Software', 'Spara is transforming inbound sales conversion through AI agents that engage, qualify, and convert website visitors into sales conversations in real-time. The company''s enterprise-grade platform delivers 10x conversion improvements by replacing traditional lead qualification processes with intelligent AI-powered conversations across chat, email, and voice channels.', ARRAY['David Walker', 'Zander Pease'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Solver', 'solver', 'https://radical.vc/portfolio/solver/', 2023, ARRAY['Software'], 'Software', 'Complete tasks, not code', ARRAY['Software'], 'Software', 'Solver completes tasks, not code. Powered by proprietary models and featuring a brand new out-of-the-editor UX, Solver is an agent that completes repository-level tasks directly from natural instructions — even text taken verbatim from an issue tracker. Solver is a "full stack" ML company on a mission to radically improve developer productivity: they build their own datasets, models, platform, and user experience. Solver has built a suite of novel foundation models over what we believe to be the most comprehensive software engineering dataset in existence today', ARRAY['Mark Gabel', 'Daniel Lord'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Synex', 'synex', 'https://radical.vc/portfolio/synex/', 2020, ARRAY['Biotechnology', 'Healthcare'], 'Biotechnology', 'Non-invasive blood monitoring technology', ARRAY['Biotechnology', 'Healthcare'], 'Biotechnology', 'Using magnetic resonance, the same underlying principle used in Magnetic Resonance Imaging (MRI), Synex is building wearable devices that would tell a person, in real time, how their body is performing by measuring glucose, lactate, and ketones – critical metabolites that affect everything from weight gain to athletic performance to the likelihood of developing diabetes. Glucose monitoring, one the most common monitoring use-cases, currently relies on an antiquated and barbaric approach involving regular pin pricks and test strips. Synex''s combination of machine learning and novel magnetic resonance technology is non-invasive technology that introduces the possibility of an entirely new category of applications to enable everyone to understand their bodies in real-time.', ARRAY['Ben Nashman'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Twelve Labs', 'twelve-labs', 'https://radical.vc/portfolio/twelve-labs/', 2022, ARRAY['Search', 'Software'], 'Search', 'Ctrl-F for Video', ARRAY['Search', 'Software'], 'Search', 'Eighty percent of the world''s data now resides in video form. Almost every part of our lives is deeply rooted in video– from organizational knowledge, meetings, and communications, to online learning, to our entertainment needs. Gen-Zers spend one-third of their waking hours watching or creating content. Twelve Labs'' innovative API makes it possible for any company to unlock the power of video for the first time. The company''s proprietary video understanding AI system can locate exact moments almost instantly across massive video archives – and makes video search as fast and easy as CTRL-F.', ARRAY['Jae Lee', 'Aiden Lee', 'SJ Kim', 'Soyoung Lee', 'David Chung'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Ubenwa', 'ubenwa', 'https://radical.vc/portfolio/ubenwa/', 2022, ARRAY['Healthcare'], 'Healthcare', 'Helping parents and doctors interpret the infant cry', ARRAY['Healthcare'], 'Healthcare', 'Ubenwa is a pioneering developer of diagnostic software for the rapid detection of medical anomalies in infant cry sounds. Ubenwa is working with hospital networks around the world to build a platform for sound-based diagnostic tools, combining groundbreaking AI research and clinical insights.', ARRAY['Charles Onu'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Unblocked', 'unblocked', 'https://radical.vc/portfolio/unblocked/', 2025, ARRAY['Software'], 'Software', 'AI-powered developer productivity platform', ARRAY['Software'], 'Software', 'Unblocked is a contextual code intelligence platform that helps developers understand the "why" behind their code, not just the "what." The company''s AI-powered solution surfaces critical context about code intent, history, and connections, enabling teams to navigate complex codebases without getting stuck on mysterious legacy systems. At its core, Unblocked acts as a "collective memory" for code, connecting scattered information across development tools to provide rich context right when developers need it. As AI generates more code and original authors move on, the platform ensures that future maintainers are not left conducting digs through commit logs and sparse documentation. Engineering teams describe Unblocked as having "another expert on the team, available 24/7."', ARRAY['Dennis Pilarinos'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Unlearn', 'unlearn', 'https://radical.vc/portfolio/unlearn/', 2022, ARRAY['Data', 'Healthcare'], 'Data', 'Accelerating clinical trials with AI', ARRAY['Data', 'Healthcare'], 'Data', 'San Francisco-based Unlearn has devised a powerful way to apply AI to improve clinical trials. Using advanced biostatistics and machine learning, Unlearn creates "digital twins" of clinical trial participants, reducing the number of actual humans that need to be recruited for control arms. This makes clinical trials cheaper and faster to execute, ultimately enabling life-changing therapeutics to reach patients sooner.', ARRAY[]::text[], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Untether AI', 'untether-ai', 'https://radical.vc/portfolio/untether-ai/', 2019, ARRAY['Semiconductors'], 'Semiconductors', 'Unlocking the power of AI in a single chip', ARRAY['Semiconductors'], 'Semiconductors', 'There is an expanding yet unmet need for inference applications, where AI is required to make rapid, real-world determinations. Much of that demand is for "on device" capabilities – high-volume AI computations that can''t rely on sending data to the cloud. Untether AI is using a market-leading architecture to create a high performance, ultra-efficient and scalable chip to meet these market demands. Untether AI''s chip has the potential to disrupt a range of industries, from data centers, autonomous vehicles, vision processing and other embedded applications.', ARRAY['Raymond Chik', 'Martin Snelgrove', 'Darrick Wiebe'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Vizcom', 'vizcom', 'https://radical.vc/portfolio/vizcom/', 2025, ARRAY['Software'], 'Software', 'Transform your sketches into renders and 3D models in seconds', ARRAY['Software'], 'Software', 'Vizcom is transforming industrial design with AI-powered software that turns hand-drawn sketches into photorealistic renderings in seconds. The company''s platform enables professional designers to rapidly iterate on concepts for physical products, from automotive interiors to footwear, accelerating what once took hours into mere moments. Unlike consumer-focused generative AI tools, Vizcom is built specifically for professional workflows, offering granular control through an iterative process that combines sketching, natural language commands, and AI-assisted rendering. The platform''s infinite canvas integrates seamlessly with existing design tools while providing advanced capabilities including texture control, lighting effects, and 3D modeling integration.', ARRAY['Jordan Taylor', 'Kaelan Richards'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('V7', 'v7', 'https://radical.vc/portfolio/v7/', 2022, ARRAY['Data', 'Software'], 'Data', 'Turn Data into Software', ARRAY['Data', 'Software'], 'Data', 'Machine learning-powered computer vision models are helping tackle a range of challenges facing society today, from spotting cancers to robotic farming. But when building an ML system, 80% of a team''s time is spent managing training data. This is a slow process that helps refine and augment the "knowledge" that models have learned by having humans perform laborious, manual labeling tasks. V7 automates the labeling process, allowing companies to solve data labeling tasks ten times more quickly. The company''s unique "programmatic labeling" workflows use AI models and minimal human steering to apply labels to data at scale.', ARRAY['Alberto Rizzoli', 'Simon Edwardsson'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Waabi', 'waabi', 'https://radical.vc/portfolio/waabi/', 2021, ARRAY['Data', 'Supply Chain', 'Transportation'], 'Data', 'Solving self-driving', ARRAY['Data', 'Supply Chain', 'Transportation'], 'Data', 'Autonomous vehicles represent one of the most exciting possibilities in AI. We dream about safer roads with fewer accidents; a society with improved mobility for all; and more efficient transport for goods and services. However, despite enormous progress in the last decade, an intelligent, fully-autonomous driving system remains elusive, and industry progress has been slower than once expected. Waabi is taking an AI-first approach to self-driving. Founded by world-renowned AI researcher Raquel Urtasun, Waabi is building virtual twins of the physical world – a "Waabi World" – where AI can learn and simulate the challenges of real-world driving. This enables Waabi to train, test, validate and continuously improve its self-driving technologies in a virtual environment, without requiring massive fleets and years of real-world training data collection. By creating a new paradigm for autonomous driving, Waabi''s approach can accelerate the industry''s shift from a decade-long, multi-trillion dollar "moonshot" into a much more approachable engineering problem.', ARRAY['Raquel Urtasun'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('World Labs', 'world-labs', 'https://radical.vc/portfolio/world-labs/', 2024, ARRAY['Software'], 'Software', 'Large World Models to perceive, generate, and interact with the 3D world', ARRAY['Software'], 'Software', 'World Labs is a spatial intelligence AI company building Large World Models (LWMs) to perceive, generate, and interact with the 3D world. The company aims to lift AI models from the 2D plane of pixels to full 3D worlds – both virtual and real – endowing them with spatial intelligence as rich as our own. Human spatial intelligence evolved over millennia; but in this time of extraordinary progress, World Labs sees the opportunity to imbue AI with this ability in the near term.', ARRAY['Fei-Fei Li', 'Justin Johnson', 'Christoph Lassner', 'Ben Mildenhall'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Writer', 'writer', 'https://radical.vc/portfolio/writer/', 2024, ARRAY['LLMs', 'Software'], 'LLMs', 'The Full-stack generative AI platform for enterprises', ARRAY['LLMs', 'Software'], 'LLMs', 'Writer builds products to help people write better. In the last few years, ''writing better'' has shifted from being about grammar and syntax to being about content generation. Writer''s platform is purpose-built for businesses to provide secure and accurate generative AI for their teams. Writer provides access to leading LLMs, as well as the tools required to build generative AI applications on top of those models and deploy them at scale. Using Writer, enterprises can build and deploy mission critical generative AI applications that can help improve productivity and efficiency across a whole range of domains.', ARRAY['May Habib', 'Waseem Alshikh'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('Xanadu', 'xanadu', 'https://radical.vc/portfolio/xanadu/', 2019, ARRAY['Semiconductors'], 'Semiconductors', 'A quantum computer for everyone', ARRAY['Semiconductors'], 'Semiconductors', 'Xanadu is building the world''s first practical quantum computer. Instead of using electrons to carry information and perform calculations, the company uses photons – particles of light – to perform extremely fast and complex computations at room temperature. Most quantum computers in development require enormous chambers where specialized chips are cooled to just above the coldest possible temperature. Xanadu''s chips aim to generate quantum effects on a thumbnail-sized chip at room temperature. The end result is a more commercially viable and scalable quantum computer.', ARRAY['Christian Weedbrook'], NULL, '2025-12-16T21:57:41Z'::timestamptz),
  ('You.com', 'you-com', 'https://radical.vc/portfolio/you-com/', 2022, ARRAY['LLMs', 'Search'], 'LLMs', 'Building a Better Search Engine', ARRAY['LLMs', 'Search'], 'LLMs', 'You.com provides accurate answers to complex questions and automates workflows to make businesses more productive. Powered by a natural language intent classifier that understands the most complex questions by turning language into structured queries, You''s AI conductor orchestrates the flow of queries across multiple private data sources, internet search, and LLMs to collect the most relevant information. The platform supports all LLMs to provide access to the best one based on a user''s question and to future proof against the rapidly evolving AI transformation. You also synthesizes all of the answers from each information source to ensure accuracy with citations and access to patent-pending real-time internet search-based fact checking – an AI polygraph.', ARRAY['Bryan McCann', 'Richard Socher'], 'https://you.com', '2025-12-16T21:57:41Z'::timestamptz),
  ('Yutori', 'yutori', 'https://radical.vc/portfolio/yutori/', 2025, ARRAY['Search', 'Software'], 'Search', 'Building personal AI assistants that automate everyday digital tasks across the web', ARRAY['Search', 'Software'], 'Search', 'Yutori is reimagining how people interact with the web through personal AI assistants capable of executing everyday digital tasks autonomously. At the core of Yutori''s innovation is its agent-first approach, which aims to create AI assistants that can reliably execute tasks ranging from scheduling and communications to authentication and transactions. Unlike current LLM-based chatbots that struggle with autonomous task completion, Yutori is developing a comprehensive solution that innovates across the entire stack — from research to product design.', ARRAY['Abhishek Das', 'Devi Parikh', 'Dhruv Batra'], NULL, '2025-12-16T21:57:41Z'::timestamptz)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  radical_portfolio_url = EXCLUDED.radical_portfolio_url,
  radical_investment_year = EXCLUDED.radical_investment_year,
  radical_all_categories = EXCLUDED.radical_all_categories,
  radical_primary_category = EXCLUDED.radical_primary_category,
  tagline = EXCLUDED.tagline,
  all_sectors = EXCLUDED.all_sectors,
  primary_sector = EXCLUDED.primary_sector,
  description = EXCLUDED.description,
  founder_names = EXCLUDED.founder_names,
  company_website_url = EXCLUDED.company_website_url,
  last_scraped_at = EXCLUDED.last_scraped_at,
  updated_at = now();

-- ============================================
-- IMPORTANT: After running this migration
-- ============================================
-- 1. Run the import script to generate embeddings:
--    cd backend && npm run import
--
-- 2. Verify companies are inserted:
--    SELECT COUNT(*) FROM companies;
--    SELECT name, slug FROM companies ORDER BY name;
--
-- 3. Verify embeddings are generated:
--    SELECT COUNT(*) FROM company_embeddings;
--    SELECT c.name, ce.source, ce.created_at 
--    FROM company_embeddings ce
--    JOIN companies c ON c.id = ce.company_id
--    ORDER BY c.name;
